# Generated by Django 4.1.2 on 2022-10-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('nm', models.CharField(max_length=100)),
                ('em', models.EmailField(max_length=254)),
            ],
        ),
    ]
